### ISSUE TITLE
Is there any relationship between false positives and "rescue mapping"?

### ISSUE THREAD

**Issue by jamestwebber** [CMU-SAFARI/Genome-on-Diet#1]
Very interesting work, and some nice results in terms of performance and sensitivity! However, the false positive rate is pretty startling--I suspect it is unacceptably high for many applications.

In section 3.6.3 I noticed this concept of "rescue mapping" when there is no hit above the user-provided threshold. I was curious: do you see any enrichment for false positives among these rescued reads? You mention that it improves sensitivity, but I am curious what the cost is.

**Comment by mealser** [comment]
Thanks James! That is a great point. The short answer is: YES, it came at cost of an increased number of false positives as you correctly guessed it. We already evaluated different rescue mapping thresholds as we mentioned at the end of page 12 (citing Supplementary Table 4) https://arxiv.org/pdf/2211.08157.pdf.

The long answer: As with any completely new read mapper, we have a large number of totally new parameters that need to be adjusted based on the desired quality. This includes adjusting trivial parameters such as the minimum alignment score for an alignment to be outputted in the SAM, the minimum number of matching seeds in an output good alignment, the rescue mapping threshold, the minimum and maximum alignment bandwidths, and many more... 
So far we pick these parameter values empirically for each data type. What could be a way to address this, is to first set the pattern into '1', which means disabling the effect of sparsifying the sequences. Then re-run the read mapping experiments and sweep the values of many of these parameters and observe what the default values need to be. There are several very recent studies that try to come up with different minimap2's default parameter values and they show improved quality and performance. We need to perform such studies for Genome-on-Diet. It is not an easy task as each evaluated setup includes 1-2 days (using 40 CPU threads) of 1) performing read mapping for the complete human genome HG002, 2) sorting and indexing the SAM, and 3) performing variant calling. I am thinking to consider only Chromosome 1 for such experiments... Any thought?

For the applications, we don't focus only on read mapping. We rather focus on enabling a new paradigm of processing the sparsified genomic data. So for containment search and metagenomic profiling, we don't observe any issue with the quality of the output. The containment search considers only the number of matched seeds and hence the alignment quality was not relevant here. For the metagenomic profiling, we already disable the rescue mapping mode (as mentioned in Section 2.3.1), so again we didn't observe any issue with the taxonomy profiling report.

**Comment by jamestwebber** [comment]
> We already evaluated different rescue mapping thresholds as we mentioned at the end of page 12 (citing Supplementary Table 4)

If I am reading this table correctly: the top row is the threshold for considering a given location, and increasing this threshold drastically reduces the number of false positives (while slightly reducing the number of true positives)? But as I understand this, you would still report the "rescue mapped" reads as well.

So my question is where those specific results are falling--maybe just the difference between enabling or disabling that setting. If most of the FPR at high _V_ is coming from the rescued reads, that suggests that it may not be worth including those results. But if it's user-configurable whether this is performed maybe that is sufficient, and users can decide.

> I am thinking to consider only Chromosome 1 for such experiments... Any thought?

I don't have an intuition for how the Diet mapping scales in terms of reference size vs number of queries, but this seems reasonable to me. I suspect you could do a parameter sweep with a fairly small number of reads, as long as you had a good diversity of read qualities (perhaps sampled from the different result bins of table 2).

**Comment by mealser** [comment]
> If I am reading this table correctly: the top row is the threshold for considering a given location, and increasing this threshold drastically reduces the number of false positives (while slightly reducing the number of true positives)? 

Yes, you did read the table correctly. We use the parameter -n 0.9,0.25. ---> 0.9 means we require 90% of all extracted seeds from a read to match around a mapping location. 0.25 is the recovery threshold, so we require 25% of all extracted seeds from a read to match around a mapping location. 

> But as I understand this, you would still report the "rescue mapped" reads as well.

Yes. Using a parameter of -n 0.9,0.25 means we consider high-quality reads that have >=90% of seeds matched with the reference genome + all reads that have between 25% to 90% as rescue mapped reads.

> So my question is where those specific results are falling--maybe just the difference between enabling or disabling that setting. If most of the FPR at high V is coming from the rescued reads, that suggests that it may not be worth including those results. But if it's user-configurable whether this is performed maybe that is sufficient, and users can decide.

This is indeed a user-configurable parameter (same as all other parameters). To simply disable it, you can use -n 0.9,0.9 or so. As the length and the window size of the minimizers (k,w) have also an effect on the need of the rescue mapping, it is still up to the user to use it.

> I suspect you could do a parameter sweep with a fairly small number of reads, as long as you had a good diversity of read qualities (perhaps sampled from the different result bins of table 2).

I like your idea of downsampling the read set to only these mapped to a limited region. Brilliant! 
The downside of using a single chromosome would be the inability to evaluate complex SVs...

Thanks a lot for the suggestions and questions!

**Comment by mealser** [comment]
We recently released a new version of Genome-on-Diet with different SAM quality control algorithms. Here is an overview of the current results: https://raw.githubusercontent.com/CMU-SAFARI/Genome-on-Diet/main/RawResults/GDiet-vs-minimap2.png. More details can be found in the paper: https://arxiv.org/abs/2211.08157
